<html>
<head>
    <title>Pokemon Mania : the Index Page</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" >
    <link rel="stylesheet" href="/css/bootstrap-responsive.min.css" type="text/css" >
</head>
    <body>
        <section>
            <header>
                <h1>Pokemon Mania : A Zend Framework Project about Pokemons of course</h1>
                <nav>
                    <ul>
                        <li>
                            <a href="<?php echo $this->baseUrl('/') ?>">Start Page</a>
                            <a href="<?php echo $this->baseUrl('/pokemons/') ?>">Pokemons</a>
                            <a href="<?php echo $this->baseUrl('/pokemons/') ?>">Contact Us !</a>
                        </li>
                    </ul>
                </nav>
            </header>
            <section>
                <p>It's non a beautifull project because we don't have time to make graphism.</p>
                <p>We love catch and watch Pokemons</p>
                <p>And another silly things to do ... yet ?</p>
            </section>
            <footer>
                <p>
                    Credentials and coming soon, a debug toolbar "a la Symfony 2" but in worse...
                </p>
            </footer>
        </section>
    <script type="javascript" src="/js/jquery-1.7.1.min.js"></script>
    <script type="javascript" src="/js/bootstrap.min.js"></script>
    </body>

</html>