<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Adding a Pokemon</title>
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/bootstrap.min.css') ?>" type="text/css" >
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/bootstrap-responsive.min.css') ?>" type="text/css" >
</head>
<section>
    <header>
        <h1>Pokemon Mania : A Zend Framework Project about Pokemons of course</h1>
        <nav>
            <ul>
                <li>
                    <a href="<?php echo $this->baseUrl('/pokemons/') ?>">Pokemons</a>
                    <a href="<?php echo $this->baseUrl('/pokemons/contact') ?>">Contact Us !</a>
                </li>
            </ul>
        </nav>
    </header>
    <section>
        <?php echo $this->form ?>
    </section>
</section>
<script type="javascript" src="<?php echo $this->baseUrl('js/jquery-1.7.1.min.js') ?>"></script>
<script type="javascript" src="<?php echo $this->baseUrl('js/bootstrap.min.js') ?>"></script>
</body>
</html>