<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>pokemonMania : un site trop cool !</title>
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/bootstrap.min.css') ?>" type="text/css" >
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/bootstrap-responsive.min.css') ?>" type="text/css" >
    <script type="text/javascript"> 
      function Lien() {
      	i = document.Choix.Liste.selectedIndex;
      	if (i == 0) return;
      	url = document.Choix.Liste.options[i].value;
      	parent.location.href = url;
      }
    </script> 
</head>
<body>
<section>
    <header>
        <h1>Pokemon Mania : A Zend Framework Project about Pokemons of course</h1>
        <nav>
            <ul>
                <li>
                    <a href="<?php echo $this->baseUrl('/pokemons/') ?>">Pokemons</a>
                    <a href="<?php echo $this->baseUrl('/pokemons/contact') ?>">Contact Us !</a>
                </li>
            </ul>
        </nav>
          <form name="Choix">
              <select name="Liste" onChange="Lien()">
                  <option value="<?php echo $this->baseUrl('/pokemons/') ?>">&nbsp;</option>
                  <option value="<?php echo $this->baseUrl('/pokemons/index/config/value/ini') ?>">Ini</option>
                  <option value="<?php echo $this->baseUrl('/pokemons/index/config/value/php') ?>">Php</option>
                  <option value="<?php echo $this->baseUrl('/pokemons/index/config/value/xml') ?>">Xml</option>
                  <option value="<?php echo $this->baseUrl('/pokemons/index/config/value/json') ?>">Json</option>
                  <option value="<?php echo $this->baseUrl('/pokemons/index/config/value/yaml') ?>">Yaml</option>
              </select>
          </form>
    </header>
    <section>
        <h2>Pokemons</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Picture</th>
                <th>Description</th>
                <th></th>
            </tr>
            <?php foreach ($this->pokemons as $key => $pokemon): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->baseUrl('/pokemons/index/show/id/' . $pokemon->id) ?>">
                        <?php echo $pokemon->name ?>
                    </a>
                </td>
                <td>
                    <?php echo '<img src="' . $pokemon->picture . '" />' ?>
                </td>

                <td>
                    <?php echo $pokemon->description ?>
                </td>
                <td>
                    <a href="<?php echo $this->baseUrl('/pokemons/index/edit/id/' . $pokemon->id) ?>">Edit</a>
                    <a href="<?php echo $this->baseUrl('/pokemons/index/del/id/' . $pokemon->id) ?>">Delete</a>
                </td>
            </tr>
            <?php endforeach ?>
        </table>
        <a href="<?php echo $this->baseUrl('/pokemons/index/add') ?>">Catch a new Pokemon !</a>
        <a href="<?php echo $this->baseUrl('/pokemons/index/pdf') ?>" target="_blank">Export the pokedex in PDF !</a>
        <a href="<?php echo $this->baseUrl('/pokemons/index/csv') ?>" target="_blank">Export the pokedex in XLS !</a>
        <a href="<?php echo $this->baseUrl('/pokemons/index/mail') ?>">Send by mail my pokedex</a>

    </section>
</section>
<div id="pied" style="position: fixed; bottom: 0; left: 0; width: 100%; text-align: center;">
  <?php echo $this->debug; ?>
</div>
<script type="javascript" src="<?php echo $this->baseUrl('js/jquery-1.7.1.min.js') ?>"></script>
<script type="javascript" src="<?php echo $this->baseUrl('js/bootstrap.min.js') ?>"></script>
</body>
</html>