<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Adding a Pokemon</title>
</head>
<section>
    <header>
        <h1>Pokemon Mania : A Zend Framework Project about Pokemons of course</h1>
        <nav>
            <ul>
                <li>
                    <a href="<?php echo $this->baseUrl('/') ?>">Start Page</a>
                    <a href="<?php echo $this->baseUrl('/pokemons/') ?>">Pokemons</a>
                    <a href="<?php echo $this->baseUrl('/pokemons/') ?>">Contact Us !</a>
                </li>
            </ul>
        </nav>
    </header>
    <section>
        <?php echo $this->form ?>
    </section>
</section>

</body>
</html>