<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Titre de ma page</title>
</head>


<?php if ($this->pokemon): ?>
    <h1><?php echo $this->pokemon->name ?></h1>
    <article>
        <img src="<?php echo $this->pokemon->picture ?>"/>
        <p>
            <?php echo $this->pokemon->description ?>
        </p>
    </article>

<?php else: ?>
    <h1>Really ? This Pokemon ?</h1>
    <?php if ($this->message): ?>
    <?php echo $this->message ?>
    <?php endif ?>
<?php endif ?>
    </body>
    </html>
